name: Deploy to GitHub Pages

on:
  # Trigger on pushes to main AND your feature branch
  push:
    branches: [ "main", "feature/additional-changes" ]
  # Optional: Also run when PR is created
  pull_request:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          
      - name: Install dependencies
        run: npm ci
          
      - name: Build
        run: npm run build
          
      - name: Deploy
        if: github.ref == 'refs/heads/main'  # Only deploy from main
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
           # Add this to force URL logging:
        env:      
          ACTIONS_STEP_DEBUG: true  # Enable debug logs